### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by echolabstech** [echolabstech/python#1]
## explanation
make tests (pytest)

## todo
- [ ] install pytest and save to requirements.txt
- [ ] capture all test cases as failing tests in test file
- [ ] test that all producers are non blocking
- [ ] test that all producers are concurrent
- [ ] test that all consumers are non blocking
- [ ] test that all consumers are concurrent
- [ ] move timers, array of book search terms, into tests
