### ISSUE TITLE
remove sensitive information from codebase

### ISSUE THREAD

**Issue by echolabstech** [echolabstech/python#2]
## explanation
remove api key & uuid from codebase, and reset api key in google

## todo
- [ ] save keys in environment variables or a file
 - add the file to gitignore
- [ ] import those variables at runtime
- [ ] reset api key in google so that anyone that looks at this repo cant reuse key
